Adding github authentication guide to lab 1
illinois-cs241/illinois-cs241.github.io pull request #297
Opened 2023-09-02 19:49 UTC by Heaper327

Adding instructions to Lab 1 on how to authenticate git without plaintext password, since many students encountered problems with cloning / pulling / pushing to their repo.

Specifically, adding instructions on how to create and authorize PA tokens, how to use `gh`, and link to github doc on authentication options.

2023-09-03 06:31 UTC, nd-0r requested changes
Looks good to me. I think this will help a lot.

2023-09-03 06:31 UTC, nd-0r commented on _docs/lockpicking_lab.md
> +```console
Probably should `sudo apt update` first

2023-09-03 14:33 UTC, xwei16 reviewed
One more thing we may want to mention: if they are on VSCode, sometimes they have to sign out then sign in after generating the token.

2023-09-07 20:15 UTC, nd-0r approved these changes

2023-09-07 20:51 UTC, xwei16 approved these changes
Lgtm!

2023-09-07 22:02 UTC, merged